# Generated by Django 3.2.6 on 2021-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstatus',
            name='email_otp',
            field=models.IntegerField(),
        ),
    ]
