# Generated by Django 3.2.6 on 2021-08-25 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_verificationstatus_email_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='verificationstatus',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
