# Generated by Django 3.2.6 on 2021-08-25 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210825_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
