# Generated by Django 3.2.6 on 2021-08-25 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210825_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationstatus',
            name='slug',
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
