# Generated by Django 3.2.6 on 2021-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210825_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
