# Generated by Django 3.2.6 on 2021-08-26 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_alter_verificationstatus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstatus',
            name='email_otp',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
