# Generated by Django 3.2.6 on 2021-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('MCQ', 'Multiple Choice Questions'), ('One Line', 'One Answer Questions')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
