# Generated by Django 3.2.6 on 2021-08-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subject_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject_info')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.quiz_types')),
            ],
        ),
    ]
