# Generated by Django 3.2.6 on 2021-08-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_question_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question_info',
            new_name='QuestionInfo',
        ),
        migrations.RenameModel(
            old_name='quiz_types',
            new_name='QuizTypes',
        ),
        migrations.RenameModel(
            old_name='subject_info',
            new_name='SubjectInfo',
        ),
    ]
