# Generated by Django 3.2.6 on 2021-08-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210819_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.questioninfo')),
            ],
        ),
    ]
