# Generated by Django 3.2.6 on 2021-08-19 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.options')),
            ],
        ),
    ]
