# Generated by Django 3.2.6 on 2021-08-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_answerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerinfo',
            name='question',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dashboard.questioninfo'),
            preserve_default=False,
        ),
    ]
