# Generated by Django 3.2.6 on 2021-08-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_answerinfo_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinfo',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.options'),
        ),
    ]
