# Generated by Django 3.2.6 on 2021-08-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210819_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.userprogress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='question',
            field=models.ManyToManyField(to='dashboard.QuestionInfo'),
        ),
    ]
