# Generated by Django 3.2.6 on 2021-08-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_report_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztypes',
            name='description',
        ),
    ]
