# Generated by Django 3.2.6 on 2021-08-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_quiztypes_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizTypes',
            new_name='QuestionType',
        ),
    ]
