# Generated by Django 3.2.6 on 2021-08-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_quiztypes_questiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
