# Generated by Django 3.2.6 on 2021-08-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerinfo',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answerinfo',
            name='option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='question',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.questioninfo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
