# Generated by Django 3.2.6 on 2021-08-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210820_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerinfo',
            old_name='is_right',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='right_choice',
            new_name='mcq_answer',
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='wrong_choice',
            new_name='one_word_answer',
        ),
        migrations.RemoveField(
            model_name='answerinfo',
            name='option',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='is_complete',
        ),
    ]
